In [1]:
#Task 1: Creating NumPy Arrays
#1. Import NumPy as np.
#2. Create the following arrays:
#• A 1D array of integers from 1 to 10
#• A 2D array of shape (3, 3) with values from 1 to 9
#• A NumPy array from the list: [10, 20, 30, 40, 50]
#3. Print:
#o Shape of each array
#• Data type of each array
import numpy as np
# Creating a 1D array of integers from 1 to 10
array_1d = np.arange(1, 11)
# Creating a 2D array of shape (3, 3) with values from 1 to 9
array_2d = np.arange(1, 10).reshape(3, 3)
# Creating a NumPy array from the list: [10, 20, 30, 40, 50]
array_from_list = np.array([10, 20, 30, 40, 50])
# Printing the shape and data type of each array
print("1D Array:")
print(array_1d)
print("Shape:", array_1d.shape)
print("Data Type:", array_1d.dtype)
print("\n2D Array:")
print(array_2d)
print("Shape:", array_2d.shape)
print("Data Type:", array_2d.dtype)
print("\nArray from List:")
print(array_from_list)
print("Shape:", array_from_list.shape)
print("Data Type:", array_from_list.dtype)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Data Type: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data Type: int64

Array from List:
[10 20 30 40 50]
Shape: (5,)
Data Type: int64


In [2]:
#Task 2: Important Mathematical Operations
#Given two arrays:
#A = np.array([10, 20, 30, 40])
#B = np.array([1, 2, 3, 4])
#Perform and print results for:
#1. Addition (A + B)
#2. Subtraction (A - B)
#3. Multiplication (A * B)
#4. Division (A /B)
#5. Power (A ** 2)
A = np.array([10, 20, 30, 40])
B = np.array([1, 2, 3, 4])
# Performing and printing results for the operations
print("Addition (A + B):")
print(A + B)
print("\nSubtraction (A - B):")
print(A - B)
print("\nMultiplication (A * B):")
print(A * B)
print("\nDivision (A / B):")
print(A / B)
print("\nPower (A ** 2):")
print(A ** 2)


Addition (A + B):
[11 22 33 44]

Subtraction (A - B):
[ 9 18 27 36]

Multiplication (A * B):
[ 10  40  90 160]

Division (A / B):
[10. 10. 10. 10.]

Power (A ** 2):
[ 100  400  900 1600]


In [3]:
#Task 3: Important NumPy Mathematical Formulas
#Given:values = np.array([2, 4, 6, 8, 10])
#Calculate:
#1. Square root of each element
#2. Exponential of each element
#3. Natural logarithm of each element
#4. Sum of all elements
#5. Cumulative sum of elements
#Use NumPy functions only.
values = np.array([2, 4, 6, 8, 10])
# Calculating and printing results for the operations
print("Square root of each element:")
print(np.sqrt(values))
print("\nExponential of each element:")
print(np.exp(values))
print("\nNatural logarithm of each element:")
print(np.log(values))
print("\nSum of all elements:")
print(np.sum(values))
print("\nCumulative sum of elements:")
print(np.cumsum(values))

Square root of each element:
[1.41421356 2.         2.44948974 2.82842712 3.16227766]

Exponential of each element:
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]

Natural logarithm of each element:
[0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]

Sum of all elements:
30

Cumulative sum of elements:
[ 2  6 12 20 30]


In [4]:
#Task 4: Aggregation Operations
#Given a 2D array:
#data = np.array([
#[10, 20, 30],
#[40, 50, 60],
#[70, 80, 90]])
#Find:
#1. Row-wise sum
#2. Column-wise sum
#3. Minimum value
#4. Maximum value
#5. Overall mean
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
# Finding and printing results for the operations
print("Row-wise sum:")
print(np.sum(data, axis=1))
print("\nColumn-wise sum:")
print(np.sum(data, axis=0))
print("\nMinimum value:")
print(np.min(data))
print("\nMaximum value:")
print(np.max(data))
print("\nOverall mean:")
print(np.mean(data))


Row-wise sum:
[ 60 150 240]

Column-wise sum:
[120 150 180]

Minimum value:
10

Maximum value:
90

Overall mean:
50.0


In [5]:
#Task 5: Statistical Operations (Core Focus)
#Given:marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])
#Calculate and print:
#1. Mean
#2. Median
#3. Variance
#4. Standard Deviation
#5. Minimum & Maximum
#6. Range (max - min)
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])
# Calculating and printing results for the operations
print("Mean:")
print(np.mean(marks))
print("\nMedian:")
print(np.median(marks))
print("\nVariance:")
print(np.var(marks))
print("\nStandard Deviation:")
print(np.std(marks))
print("\nMinimum value:")
print(np.min(marks))
print("\nMaximum value:")
print(np.max(marks))
print("\nRange (max - min):")
print(np.max(marks) - np.min(marks))


Mean:
79.25

Median:
81.5

Variance:
134.1875

Standard Deviation:
11.583932838203095

Minimum value:
60

Maximum value:
95

Range (max - min):
35


In [6]:
#Task 6: Percentiles & Sorting
#Using the same marks array:
#1. Sort the array
#2. Find:
#• 25th percentile
#• 50th percentile
#• 75th percentile
#3. Count how many students scored above the average marks
# Sorting the array
sorted_marks = np.sort(marks)
# Finding and printing percentiles
print("25th percentile:")
print(np.percentile(marks, 25))
print("\n50th percentile:")
print(np.percentile(marks, 50))
print("\n75th percentile:")
print(np.percentile(marks, 75))
# Counting how many students scored above the average marks
average_marks = np.mean(marks)
count_above_average = np.sum(marks > average_marks)
print("\nNumber of students scored above the average marks:")
print(count_above_average)


25th percentile:
70.5

50th percentile:
81.5

75th percentile:
88.5

Number of students scored above the average marks:
4


In [7]:
#Task 7: Mini Use Case: Sales Analysis
#Given daily sales data:sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
#Perform:
#1. Total weekly sales
#2. Average daily sales
#3. Highest and lowest sales day
#4. Standard deviation of sales
#5. Identify days where sales were above average
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
# Performing and printing results for the operations
print("Total weekly sales:")
print(np.sum(sales))
print("\nAverage daily sales:")
print(np.mean(sales))
print("\nHighest sales day:")
print(np.max(sales))
print("\nLowest sales day:")
print(np.min(sales))
print("\nStandard deviation of sales:")
print(np.std(sales))
print("\nDays where sales were above average:")
average_sales = np.mean(sales)
days_above_average = np.where(sales > average_sales)[0]  # Get indices of days above average
print(days_above_average)


Total weekly sales:
10700

Average daily sales:
1528.5714285714287

Highest sales day:
2000

Lowest sales day:
900

Standard deviation of sales:
345.2298849598449

Days where sales were above average:
[3 4 5 6]
